name: Deploy to VPS

on:
  push:
    branches: [master]

concurrency:
  group: deploy-to-vps
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      SSH_USER: debian
      SSH_HOST: ${{ secrets.VPS_HOST }}
      SSH_PORT: ${{ secrets.VPS_PORT }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: Install deps
        run: npm ci --no-audit --no-fund

      - name: Build (SSR included by ng build)
        env:
          NODE_OPTIONS: --max_old_space_size=4096
          CI: true
        run: npx ng build

      - name: Install Supabase client for build scripts
        run: npm i --no-audit --no-fund --no-save @supabase/supabase-js@^2

      - name: Fetch dynamic URLs (Supabase)
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
        run: node scripts/fetch-dynamic.mjs

      - name: Generate sitemap.xml and robots.txt
        env:
          PUBLIC_BASE_URL: ${{ secrets.PUBLIC_BASE_URL }}
        run: node scripts/gen_seo.mjs

      - name: Verify SEO artifacts
        run: |
          test -f dist/ragnarok/browser/robots.txt
          test -f dist/ragnarok/browser/sitemap.xml
          echo "[ok] robots & sitemap present"

      - name: Preview robots/sitemap (head)
        run: |
          sed -n '1,20p' dist/ragnarok/browser/robots.txt
          sed -n '1,20p' dist/ragnarok/browser/sitemap.xml

      - name: Validate sitemap size (rough)
        run: |
          COUNT=$(grep -c '<url>' dist/ragnarok/browser/sitemap.xml || true)
          test "$COUNT" -gt 0
          echo "[ok] urls in sitemap: $COUNT"

      - name: Pack dist (browser + server)
        run: |
          TAR_PATH="$RUNNER_TEMP/ragnarok-dist.tgz"
          echo "TAR_PATH=$TAR_PATH" >> "$GITHUB_ENV"
          tar -czf "$TAR_PATH" -C dist/ragnarok browser server
          ls -lh "$TAR_PATH"

      - name: Setup SSH
        env:
          VPS_SSH_KEY: ${{ secrets.VPS_SSH_KEY }}
          VPS_KNOWN_HOSTS: ${{ secrets.VPS_KNOWN_HOSTS }}
        run: |
          install -m 700 -d ~/.ssh
          if [ -n "${VPS_KNOWN_HOSTS:-}" ]; then
            printf "%s\n" "$VPS_KNOWN_HOSTS" > ~/.ssh/known_hosts
          else
            echo "StrictHostKeyChecking no" > ~/.ssh/config
            echo "UserKnownHostsFile /dev/null" >> ~/.ssh/config
            chmod 600 ~/.ssh/config
          fi
          install -m 600 /dev/null ~/.ssh/id_ed25519
          printf "%s\n" "$VPS_SSH_KEY" > ~/.ssh/id_ed25519

      - name: Preflight SSH check
        run: |
          : "${SSH_HOST:?Missing secret VPS_HOST}"
          : "${SSH_USER:?Missing SSH user}"
          : "${SSH_PORT:=22}"
          ssh -o BatchMode=yes -p "$SSH_PORT" "$SSH_USER@$SSH_HOST" "echo '[ssh] ok'"

      - name: Copy deploy script and dist to VPS
        run: |
          : "${SSH_PORT:=22}"
          scp -P "$SSH_PORT" scripts/deploy_dist.sh "$SSH_USER@$SSH_HOST:/tmp/ragnarok-deploy.sh"
          scp -P "$SSH_PORT" "$TAR_PATH" "$SSH_USER@$SSH_HOST:/tmp/ragnarok-dist.tgz"
          ssh -p "$SSH_PORT" "$SSH_USER@$SSH_HOST" "chmod +x /tmp/ragnarok-deploy.sh"

      - name: Run remote deploy
        run: |
          : "${SSH_PORT:=22}"
          ssh -p "$SSH_PORT" "$SSH_USER@$SSH_HOST" "/tmp/ragnarok-deploy.sh /tmp/ragnarok-dist.tgz"
